{% set name = "os-service-types" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31800299a82239363995b91f1ebf9106ac7758542a1e4ef6dc737a5932878c6c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - os_service_types

about:
  home: https://docs.openstack.org/os-service-types/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Summary of the package
  description: Python library for consuming OpenStack sevice-types-authority data.
  doc_url: https://docs.openstack.org/os-service-types/latest/
  dev_url: https://git.openstack.org/cgit/openstack/os-service-types

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
